name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: go mod download
    - name: Build
      run: go install -v ./..
    - name: Test
      run: go test -race ./..
    - name: Lint
      run: |
        go install -v github.com/golangci/golangci-lint/cmd/golangci-lint
        golangci-lint run ./...
