on: push
name: Push
jobs:
  checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: cedrickring/golang-action/go1.13@1.4.1
      with:
        args: make install test lint
